INSERT INTO Paises(Nombre, Bandera,FechaFundacion) VALUES
('Afganistán Emirato Islámico','http://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/360px-Flag_of_the_Taliban.svg.png','1-1-1'),
('Afganistán República Islámica','http://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Flag_of_Afghanistan_%282013%E2%80%932021%29.svg/270px-Flag_of_Afghanistan_%282013%E2%80%932021%29.svg.png','1-1-1'),
('Albania','http://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/252px-Flag_of_Albania.svg.png','1-1-1'),
('Alemania','http://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/300px-Flag_of_Germany.svg.png','1-1-1'),
('Andorra','http://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Andorra.svg/257px-Flag_of_Andorra.svg.png','1-1-1'),
('Angola','http://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/270px-Flag_of_Angola.svg.png','1-1-1'),
('Antigua y Barbuda','http://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Antigua_and_Barbuda.svg/270px-Flag_of_Antigua_and_Barbuda.svg.png','1-1-1'),
('Arabia Saudita','http://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/270px-Flag_of_Saudi_Arabia.svg.png','1-1-1'),
('Argelia','http://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/270px-Flag_of_Algeria.svg.png','1-1-1'),
('Argentina','http://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/288px-Flag_of_Argentina.svg.png','1-1-1'),
('Armenia','http://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Flag_of_Armenia.svg/360px-Flag_of_Armenia.svg.png','1-1-1'),
('Australia','http://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/360px-Flag_of_Australia_%28converted%29.svg.png','1-1-1'),
('Austria','http://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/270px-Flag_of_Austria.svg.png','1-1-1'),
('Azerbaiyán','http://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/360px-Flag_of_Azerbaijan.svg.png','1-1-1'),
('Bahamas','http://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Flag_of_the_Bahamas.svg/360px-Flag_of_the_Bahamas.svg.png','1-1-1'),
('Bangladés','http://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/300px-Flag_of_Bangladesh.svg.png','1-1-1'),
('Barbados','http://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Barbados.svg/270px-Flag_of_Barbados.svg.png','1-1-1'),
('Baréin','http://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Bahrain.svg/300px-Flag_of_Bahrain.svg.png','1-1-1'),
('Bélgica','http://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/208px-Flag_of_Belgium.svg.png','1-1-1'),
('Belice','http://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Flag_of_Belize.svg/300px-Flag_of_Belize.svg.png','1-1-1'),
('Benín','http://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Benin.svg/270px-Flag_of_Benin.svg.png','1-1-1'),
('Bielorrusia','http://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Belarus.svg/360px-Flag_of_Belarus.svg.png','1-1-1'),
('Birmania','http://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Flag_of_Myanmar.svg/270px-Flag_of_Myanmar.svg.png','1-1-1'),
('Bolivia','http://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Bolivia.svg/264px-Flag_of_Bolivia.svg.png','1-1-1'),
('Bosnia y Herzegovina','http://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bosnia_and_Herzegovina.svg/360px-Flag_of_Bosnia_and_Herzegovina.svg.png','1-1-1'),
('Botsuana','http://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/270px-Flag_of_Botswana.svg.png','1-1-1'),
('Brasil','http://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/257px-Flag_of_Brazil.svg.png','1-1-1'),
('Brunéi','http://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Brunei.svg/360px-Flag_of_Brunei.svg.png','1-1-1'),
('Bulgaria','http://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/300px-Flag_of_Bulgaria.svg.png','1-1-1'),
('Burkina Faso','http://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Burkina_Faso.svg/270px-Flag_of_Burkina_Faso.svg.png','1-1-1'),
('Burundi','http://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/300px-Flag_of_Burundi.svg.png','1-1-1'),
('Bután','http://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Flag_of_Bhutan.svg/270px-Flag_of_Bhutan.svg.png','1-1-1'),
('Cabo Verde','http://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Cape_Verde.svg/306px-Flag_of_Cape_Verde.svg.png','1-1-1'),
('Camboya','http://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_Cambodia.svg/282px-Flag_of_Cambodia.svg.png','1-1-1'),
('Camerún','http://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/270px-Flag_of_Cameroon.svg.png','1-1-1'),
('Canadá','http://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Canada.svg/360px-Flag_of_Canada.svg.png','1-1-1'),
('Catar','http://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/459px-Flag_of_Qatar.svg.png','1-1-1'),
('Chad','http://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Flag_of_Chad.svg/270px-Flag_of_Chad.svg.png','1-1-1'),
('Chile','http://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/270px-Flag_of_Chile.svg.png','1-1-1'),
('China','http://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/270px-Flag_of_the_People%27s_Republic_of_China.svg.png','1-1-1'),
('Chipre','http://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Cyprus.svg/270px-Flag_of_Cyprus.svg.png','1-1-1'),
('Colombia','http://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/270px-Flag_of_Colombia.svg.png','1-1-1'),
('Comoras','http://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Flag_of_the_Comoros.svg/300px-Flag_of_the_Comoros.svg.png','1-1-1'),
('Corea del Norte','http://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Flag_of_North_Korea.svg/360px-Flag_of_North_Korea.svg.png','1-1-1')

