INSERT INTO Deportes(Nombre, Foto) VALUES
('Atletismo','https://olympics.com/images/static/sports/pictograms/v2/ath.svg'),
('Bádminton','https://olympics.com/images/static/sports/pictograms/v2/bdm.svg'),
('Baloncesto','https://olympics.com/images/static/sports/pictograms/v2/bkb.svg'),
('Baloncesto 3x3','https://olympics.com/images/static/sports/pictograms/v2/bk3.svg'),
('Balonmano','https://olympics.com/images/static/sports/pictograms/v2/hbl.svg'),
('Balonmano Playa','https://olympics.com/images/static/sports/pictograms/v2/hbb.svg'),
('Béisbol 5','https://olympics.com/images/static/sports/pictograms/v2/bs5.svg'),
('Béisbol Sóftbol','https://olympics.com/images/static/sports/pictograms/v2/bsb.svg'),
('Biatlón','https://olympics.com/images/static/sports/pictograms/v2/bth.svg'),
('Bobsleigh','https://olympics.com/images/static/sports/pictograms/v2/bob.svg'),
('Boxeo','https://olympics.com/images/static/sports/pictograms/v2/box.svg'),
('Breaking','https://olympics.com/images/static/sports/pictograms/v2/bkg.svg'),
('Ciclismo BMX Freestyle','https://olympics.com/images/static/sports/pictograms/v2/bmf.svg'),
('Ciclismo BMX Racing','https://olympics.com/images/static/sports/pictograms/v2/bmx.svg'),
('Ciclismo de montaña','https://olympics.com/images/static/sports/pictograms/v2/mtb.svg'),
('Ciclismo en pista','https://olympics.com/images/static/sports/pictograms/v2/ctr.svg'),
('Ciclismo en ruta','https://olympics.com/images/static/sports/pictograms/v2/crd.svg'),
('Combinada nórdica','https://olympics.com/images/static/sports/pictograms/v2/ncb.svg'),
('Críquet','https://olympics.com/images/static/sports/pictograms/v2/ckt.svg'),
('Curling','https://olympics.com/images/static/sports/pictograms/v2/cur.svg'),
('Escalada Deportiva','https://olympics.com/images/static/sports/pictograms/v2/clb.svg'),
('Esgrima','https://olympics.com/images/static/sports/pictograms/v2/fen.svg'),
('Esquí acrobático','https://olympics.com/images/static/sports/pictograms/v2/frs.svg'),
('Esquí alpino','https://olympics.com/images/static/sports/pictograms/v2/alp.svg'),
('Esquí de fondo','https://olympics.com/images/static/sports/pictograms/v2/ccs.svg'),
('Esquí de montaña','https://olympics.com/images/static/sports/pictograms/v2/smt.svg'),
('Flag Football','https://olympics.com/images/static/sports/pictograms/v2/flf.svg'),
('Fútbol','https://olympics.com/images/static/sports/pictograms/v2/fbl.svg'),
('Fútbol Sala','https://olympics.com/images/static/sports/pictograms/v2/fut.svg'),
('Gimnasia Acrobática','https://olympics.com/images/static/sports/pictograms/v2/gac.svg'),
('Gimnasia Artística','https://olympics.com/images/static/sports/pictograms/v2/gar.svg'),
('Gimnasia en Trampolín','https://olympics.com/images/static/sports/pictograms/v2/gtr.svg'),
('Gimnasia Rítmica','https://olympics.com/images/static/sports/pictograms/v2/gry.svg'),
('Golf','https://olympics.com/images/static/sports/pictograms/v2/glf.svg'),
('Halterofilia','https://olympics.com/images/static/sports/pictograms/v2/wlf.svg'),
('Hípica','https://olympics.com/images/static/sports/pictograms/v2/equ.svg'),
('Hockey sobre Césped','https://olympics.com/images/static/sports/pictograms/v2/hoc.svg'),
('Hockey sobre hielo','https://olympics.com/images/static/sports/pictograms/v2/iho.svg'),
('Judo','https://olympics.com/images/static/sports/pictograms/v2/jud.svg'),
('Karate','https://olympics.com/images/static/sports/pictograms/v2/kte.svg'),
('Lacrosse','https://olympics.com/images/static/sports/pictograms/v2/lax.svg'),
('Lucha','https://olympics.com/images/static/sports/pictograms/v2/wre.svg'),
('Luge','https://olympics.com/images/static/sports/pictograms/v2/lug.svg'),
('Natación','https://olympics.com/images/static/sports/pictograms/v2/swm.svg'),
('Natación Artística','https://olympics.com/images/static/sports/pictograms/v2/swa.svg'),
('Natación en aguas abiertas','https://olympics.com/images/static/sports/pictograms/v2/ows.svg'),
('Patinaje artístico','https://olympics.com/images/static/sports/pictograms/v2/fsk.svg'),
('Patinaje de velocidad','https://olympics.com/images/static/sports/pictograms/v2/ssk.svg'),
('Patinaje de velocidad en pista corta','https://olympics.com/images/static/sports/pictograms/v2/stk.svg'),
('Patinaje de velocidad sobre ruedas','https://olympics.com/images/static/sports/pictograms/v2/rol.svg'),
('Pentatlón Moderno','https://olympics.com/images/static/sports/pictograms/v2/mpn.svg'),
('Piragüismo en eslalon','https://olympics.com/images/static/sports/pictograms/v2/csl.svg'),
('Piragüismo en esprint','https://olympics.com/images/static/sports/pictograms/v2/csp.svg'),
('Remo','https://olympics.com/images/static/sports/pictograms/v2/row.svg'),
('Remo coastal','https://olympics.com/images/static/sports/pictograms/v2/roc.svg'),
('Rugby 7','https://olympics.com/images/static/sports/pictograms/v2/ru7.svg'),
('Salto de esquí','https://olympics.com/images/static/sports/pictograms/v2/sjp.svg'),
('Saltos','https://olympics.com/images/static/sports/pictograms/v2/div.svg'),
('Skateboarding','https://olympics.com/images/static/sports/pictograms/v2/skb.svg'),
('Skeleton','https://olympics.com/images/static/sports/pictograms/v2/skn.svg'),
('Snowboard','https://olympics.com/images/static/sports/pictograms/v2/sbd.svg'),
('Squash','https://olympics.com/images/static/sports/pictograms/v2/squ.svg'),
('Surf','https://olympics.com/images/static/sports/pictograms/v2/srf.svg'),
('Taekwondo','https://olympics.com/images/static/sports/pictograms/v2/tkw.svg'),
('Tenis','https://olympics.com/images/static/sports/pictograms/v2/ten.svg'),
('Tenis de Mesa','https://olympics.com/images/static/sports/pictograms/v2/tte.svg'),
('Tiro','https://olympics.com/images/static/sports/pictograms/v2/sho.svg'),
('Tiro con Arco','https://olympics.com/images/static/sports/pictograms/v2/arc.svg'),
('Triatlón','https://olympics.com/images/static/sports/pictograms/v2/tri.svg'),
('Vela','https://olympics.com/images/static/sports/pictograms/v2/sal.svg'),
('Voleibol','https://olympics.com/images/static/sports/pictograms/v2/vvo.svg'),
('Voleibol Playa','https://olympics.com/images/static/sports/pictograms/v2/vbv.svg'),
('Waterpolo','https://olympics.com/images/static/sports/pictograms/v2/wpo.svg'),
('Wushu','https://olympics.com/images/static/sports/pictograms/v2/wsu.svg');
